### ISSUE TITLE
Lenker til dokumenter

### ISSUE THREAD

**Issue by aatjora** [kartverket/SOSI-Veileder-for-utarbeidelse-av-SOSI-produktspesifikasjoner#1]
Det opprinnelige dokumentet viser til andre dokumenter uten å lenke til dem.
Dette burde vi kunne rette, slik at henvisningene har lenke.

**Comment by josteinAmlien** [comment]
Prod.spek.standarden ligger her : https://register.geonorge.no/sosi-standarden/sosi-produktspesifikasjoner-krav-og-godkjenning

**Comment by josteinAmlien** [comment]
Rammeverksdokumentet (kap 1.4.4) https://register.geonorge.no/subregister/versjoner/nasjonalt-rammeverk-for-geografisk-informasjon/kartverket/rammeverksdokumentet/kartverket/teknologisk-rammeverk-for-den-geografiske-infrastrukturen

**Comment by josteinAmlien** [comment]
Veileder til kart og planforskriften (kap 1.4.4) https://www.regjeringen.no/no/dokumenter/veiledning-til-forskrift-om-kart-stedfestet-informasjon-arealformal-og-digitalt-planregister/
Teksten kan modifiseres til at dokuemntet gir føringer for DOK-data til utabeidelse av SOSI prod.spekker

**Comment by josteinAmlien** [comment]
Lenke til ekspempeldokumentet legges inn i kap 1.4.6  når det er publisert som html.
Teksten kan modifiseres til:

1.4.6 Maler og ekspempler

Vi anbefaler å benytte AsciiDoc til å lage produktspesifikasjoner. Dokumenter på dette formatet kan publiseres som html.

Last ned [adoc-mal for SOSI produktspesifikasjonsdokument]{https://www.geonorge.no/globalassets/geonorge2/standardisering/maler/asciidocmaler.zip} og ta utgangspunkt i denne for å skrive produktspesifikasjonen.

Se [Eksempel på SOSI produktspesifikasjonsdokument]{url}, som er et fiktivt eksempel på en SOSI produktspesifikasjon i form av en html-fil som følger malen. 
Se også [eksempeldokumentet på adoc-format]{url} for å se hvordan adoc-syntaksen er.

**Comment by josteinAmlien** [comment]
Kap 1.4.2: 
https://www.geonorge.no/Geodataarbeid/standardisering/standarder-under-sosi-paraplyen/

**Comment by josteinAmlien** [comment]
Kap 1.4.1:
Alle veilederne referert her er/blir nå publisert som html. 
Legg inn lenkene til html-dokumentene

**Comment by aatjora** [comment]
Rettet som del av PR #11

**Comment by aatjora** [comment]
Lukkes
