### ISSUE TITLE
Feil henvisning til hovedkapitel i standarden

### ISSUE THREAD

**Issue by josteinAmlien** [kartverket/SOSI-Veileder-for-utarbeidelse-av-SOSI-produktspesifikasjoner#3]
Kap 4 inneholder en omtale av hvert av kapitlene i prod.spekken.
Disse innledes med en henvisning til hvor i standarden dette er spesifisert.
Henvisningen er feil for prod.spekkens kap 1 og 2
De skal henvise til standardens kap 11 og 12, ikke 1 og 2

Dette bør rettes før veiledereren publiseres som html

**Comment by aatjora** [comment]
Rettet i PR #11
