### ISSUE TITLE
Henvisning til ekspempeldokuemnt 

### ISSUE THREAD

**Issue by josteinAmlien** [kartverket/SOSI-Veileder-for-utarbeidelse-av-SOSI-produktspesifikasjoner#5]
Henvisningen i kap 1.4.5 til ekspempeldokuemnt peker til et Word-dokumewnt.
Den bør rettes til å peke på html-utgaven av eksemplet. 
Fjern også referansen til / omtalen av  Word-formatet i teksten.

**Comment by aatjora** [comment]
Rettet
